name: category_navigator
description: A flutter ui package for cool navigation bar with a lot of customization options
version: 1.1.6
homepage: https://github.com/AnonymousAliensX/category_navigator
Maintainer: Rahul Saini (@dynamicrahulsaini)

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0